Repository memoriesadrift/we-find, pull requests merged in 2021-05, with the labels that each got.

#23 Trying to make the CourseDetailScreen utilize course objects. Stuck at reading a mock XML from a file
  lib/data/course.dart
  lib/exeptions/exceptions.dart
  lib/model/modelTranslate.dart
  lib/screens/CourseDetailScreen.dart
  lib/screens/HomeScreen.dart
  lib/widgets/course_detail_widgets.dart
  pubspec.lock
  pubspec.yaml
Labels: needs work

#29 Started work on course directore screen
  lib/data/coursedir.dart
  lib/model/modelWrapped.dart
  lib/screens/CourseDetailScreen.dart
  lib/screens/CourseDirectoryScreen.dart
  lib/screens/HomeScreen.dart
  lib/screens/StudyModuleScreen.dart
  lib/styles/style_consts.dart
  lib/styles/theme.dart
  lib/widgets/StudyModuleWidget.dart
  lib/widgets/course_detail_widgets.dart
Labels: needs review

#37 I3 search result screen draft
  lib/screens/CourseDirectoryScreen.dart
  lib/screens/HomeScreen.dart
  lib/screens/SearchResultsScreen.dart
  lib/service/ufind_service.dart
  lib/widgets/CourseWidget.dart
  lib/widgets/search_bar.dart
Labels: needs review

#43 changed passing themeData to passing context. closes #42
  lib/screens/CourseDetailScreen.dart
  lib/screens/CourseDirectoryScreen.dart
  lib/screens/SearchResultsScreen.dart
  lib/screens/StudyModuleScreen.dart
Labels: needs review

#63 Make the Course Directory fetch items from the API
  lib/data/course_dir.dart
  lib/model/model_wrapped.dart
  lib/screens/course_directory_screen.dart
  lib/screens/home_screen.dart
  lib/screens/study_module_screen.dart
  lib/service/ufind_service.dart
  lib/widgets/course_directory_widgets.dart
  lib/widgets/study_module_widget.dart
Labels: needs review

#69 rename old readme, create HCI readme
  APPREADME.md
  README.md
Labels: documentation

#65 Advanced Search Screen Implemntation
  lib/screens/advaned_search_screen.dart
  lib/screens/home_screen.dart
  lib/service/ufind_service.dart
  lib/widgets/advanced_search_widgets.dart
Labels: needs work, new feature

#74 language&translation. closes #71
  lib/language/language_constants.dart
  lib/model/model_wrapped.dart
  lib/providers/lang_provider.dart
  lib/screens/advaned_search_screen.dart
  lib/screens/course_directory_screen.dart
  lib/screens/home_screen.dart
  lib/screens/search_results_screen.dart
  lib/widgets/advanced_search_widgets.dart
  lib/widgets/course_detail_widgets.dart
  lib/widgets/course_directory_widgets.dart
  lib/widgets/course_widget.dart
  lib/widgets/favourite_tile.dart
  lib/widgets/search_bar.dart
Labels: needs review
